# Generated by Django 5.2.5 on 2025-08-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Property name (e.g., Color, Size, Material)', max_length=100)),
                ('value', models.CharField(help_text='Property value (e.g., Red, Large, Cotton)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Product Properties',
                'ordering': ['order', 'key'],
                'unique_together': {('product', 'key')},
            },
        ),
    ]
