services:
  - type: web
    name: shopcore-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopcore.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: shopcore-db
          property: connectionString
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: MEDIA_ROOT
        value: /opt/render/project/src/media

databases:
  - name: shopcore-db
    databaseName: shopcore
    user: shopcore_user
    plan: free
